language: cpp
compiler:
  - g++-4.8
 
before_script:
  - sudo apt-get install libsfml-dev
  - sudo apt-get install libgtest-dev
  - sudo apt-get install cmake
  - cd /usr/src/gtest
  - ls -a
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd /home/travis/build/UsagiLoliChan/t  

script: 
  - make default 
  - cd build
  - cmake ..
  - make
  - cd ..
  - launch_test

