language: cpp
compiler:
  - g++-4.8

before_script:
  - sudo apt-get install libsfml-dev
  - sudo apt-get install libgtest-dev
  - sudo apt-get install cmake
  - cd /usr/src/gtest
  - la
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib

script: make default && make test && make launch_test
